POST http://localhost:8080/callstart/call_uuid_1
Content-Type: application/json

{
  "data": {
    "callStartTime": "20230505121212",
    "callEndTime": "",
    "dnis": "23059",
    "currentTime": "20230505131313",
    "ani": "01020232023",
    "callType": "1",
    "channel": "1",
    "sessionId": "20628a59-1753-415d-a123-16e4ec77d498",
    "scaIp": "106.246.239.221",
    "botcode": "a1d75ffe-6368-4c4f-be95-2326f87552fa",
    "direction": "X"
  }
}